templates:
  params:
    author-name: Jakob Rath
    author-email: git@jakobrath.eu
    copyright: 'Copyright: (c) 2020 Jakob Rath'
    github-username: JakobR
# allow-newer: true

ghc-options:
    "$everything": -haddock
