# .zprofile

# Why do we do this here in .zprofile?
# Because on macOS, the following happens:
# - ...
# - $ZDOTDIR/.zshenv
# - ...
# - /etc/profile is sourced, which calls /usr/libexec/path_helper, and this puts /usr/bin etc. in front
# - $ZDOTDIR/.zprofile is sourced
# - ...
#
# So to override system binaries we need to add the path in this file
# See https://superuser.com/a/1464744

# Set up $PATH, but only if we're not in a nix-shell
# (inside nix-shell, we will get the correct PATH and other variables from the outer shell)
if [[ ! -v IN_NIX_SHELL ]] then
    if [[ "$OSTYPE" =~ ^darwin ]] then
        # Support multiple homebrew installations on Apple Silicon Macs
        # See https://stackoverflow.com/a/68443301
        if [[ "$(arch)" = "arm64" ]] then
            eval "$(/opt/homebrew/bin/brew shellenv)"
        else
            eval "$(/usr/local/bin/brew shellenv)"
        fi
    fi
fi


# vim: ft=zsh
